



session_options:
  countdown_second: 120
  # phase 1 : alone => 120 seconds
  # phase 2 : duel => 240 seconds
  # phase 3 : four => 240 seconds
  feed_interval_second: 2
  participants: # session type = quest when 1 participant, duel when 2 participants, scuffle when 3 or more participants
   - "AmaBot"
   - "BridgeTheBrick"
   - "BwT"
   - "GEMinator"
   - "RequiemForABot"
   - "TeamRocket"
   - "Terminator"
   - "TeslaCybertruck"

  ##improve: add a way to show/hide each element in output video
#    show_walls: false
#    show_grounds: true
#    show_bots: true
#    show_goals: true

# Unleash the Bricks Configuration
window:
  width: 1920
  height: 1080

camera:
  calibration_file: "/home/taccart/development/github_perso/amaker-path-capture/TALogitechHDWebcamB910_calibration.npz" # see calibration.py
  number: -1    # Use -1 to interactively select from list of available cams

communication:
  serial_port: "/dev/ttyACM1"
  serial_speed: 115200

logs:
  max_count: 20

recording:
  enabled: True
  feed_enabled:   True
  path: "/tmp/" # Path to save recordings

# tags -> Bot configurations
#known_tags:
#  300:
#    name: "East"
#    type: "wall"
#  301:
#    name: "South"
#    type: "wall"
#  302:
#    name: "West"
#    type: "wall"
#  303:
#    name: "North"
#    type: "wall"
#
#  310:
#    name: "South-East"
#    type: "ground"
#  311:
#    name: "South-West"
#    type: "ground"
#  312:
#    name: "North-West"
#    type: "ground"
#  313:
#    name: "North-East"
#    type: "ground"
known_tags:
  74:
    type: "bot"
    name: "AmaBot"
    color: [230, 159, 0]  # E69F00 orange
  77:
    type: "bot"
    name: "BridgeTheBrick"
    color: [86, 180, 233]  # 56B4E9 sky blue
  73:
    type: "bot"
    name: "BwT"
    color: [0, 158, 115]  # 009E73 bluish green
  78:
    type: "bot"
    name: "GEMinator"
    color: [240, 228, 66]  # F0E442 yellow
  79:
    type: "bot"
    name: "RequiemForABot"
    color: [0, 114, 178]  # 0072B2 blue
  75:
    type: "bot"
    name: "TeamRocket"
    color: [213, 94, 0]  # D55E00 vermillion
  76:
    type: "bot"
    name: "Terminator"
    color: [0, 0, 0]  # 000000 black
  72:
    type: "bot"
    name: "TeslaCybertruck"
    color: [204, 121, 167]  # CC79A7 reddish purple
  400:
    type: "goal"
    name: "Amabot"
    color: [230, 159, 0]  # E69F00 orange (matches AmaBot)
  401:
    type: "goal"
    name: "BridgeTheBricks"
    color: [86, 180, 233]  # 56B4E9 sky blue (matches BridgeTheBrick)
  402:
    type: "goal"
    name: "BwT"
    color: [0, 158, 115]  # 009E73 bluish green (matches BwT)
  403:
    type: "goal"
    name: "Geminator"
    color: [240, 228, 66]  # F0E442 yellow (matches GEMinator)
  404:
    type: "goal"
    name: "RequiemForABot"
    color: [0, 114, 178]  # 0072B2 blue (matches RequiemForABot)
  405:
    type: "goal"
    name: "Rocket"
    color: [213, 94, 0]  # D55E00 vermillion (matches TeamRocket)
  406:
    type: "goal"
    name: "Terminator"
    color:  [0, 0, 0] # 000000 reddish purple (matches Terminator)
  407:
    type: "goal"
    name: "TeslaCybertruck"
    color: [204, 121, 167]   #  CC79A7 black (matches TeslaCybertruck)